#!/bin/bash

# Development Startup Script for IBFly Simulator
# This script starts both frontend and backend services
# Generated by Agent OS to prevent setup amnesia

set -e  # Exit on error

echo "🚀 Starting IBFly Simulator Development Environment"
echo "================================================="

# Load environment variables
if [ -f .env ]; then
    echo "📋 Loading backend environment from .env"
    export $(grep -v '^#' .env | xargs)
fi

if [ -f .env.local ]; then
    echo "📋 Loading frontend environment from .env.local"
    export $(grep -v '^#' .env.local | xargs)
fi

# Get ports from environment or use defaults
BACKEND_PORT=${API_PORT:-${PORT:-8000}}
FRONTEND_PORT=${PORT:-3000}

# Backend startup
echo ""
echo "📡 Starting Backend Server on port $BACKEND_PORT..."
cd backend 2>/dev/null || echo "Backend directory not found - will be created during implementation"

if [ -d . ] && [ -f main.py ]; then
    source .venv/bin/activate || uv venv && source .venv/bin/activate
    uv pip install -r requirements.txt 2>/dev/null || echo "Requirements.txt not found yet"
    uvicorn main:app --reload --port $BACKEND_PORT &
fi

# Frontend startup  
echo ""
echo "🎨 Starting Frontend Server on port $FRONTEND_PORT..."
cd ../frontend 2>/dev/null || cd .. 2>/dev/null || echo "Frontend directory not found - will be created during implementation"

if [ -d . ] && [ -f package.json ]; then
    yarn install 2>/dev/null || echo "Package.json not found yet"
    yarn dev &
fi

echo ""
echo "✅ Development servers will start when implemented!"
echo "   Frontend: http://localhost:$FRONTEND_PORT"
echo "   Backend:  http://localhost:$BACKEND_PORT"
echo ""
echo "Press Ctrl+C to stop all services"
wait